[Unit]
After=systemd-tmpfiles-setup.service
Wants=systemd-tmpfiles-setup.service

[Service]
ExecStartPre=/usr/bin/findmnt --noheadings --types tmpfs --mountpoint /run
ExecStartPre=/usr/bin/systemd-tmpfiles --create /etc/tmpfiles.d/vanpi-network.conf
