import { decodeComputeReport } from './decoder';
import type { ComputeRange, ComputeReport } from './types';

export function computePayload(range: ComputeRange = 168) {
  return {
    ok: true,
    generated_at: 1_775_000_000,
    range_hours: range,
    status: {
      configured: true,
      available: true,
      busy: false,
      queued: 1,
      running: 0,
      local_running: 0,
      slots_total: 10,
      slots_busy: 3,
      slots_available: 7,
      workers: [
        {
          worker: 'm4mac',
          placement: 'remote',
          seen_at: 1_774_999_995,
          age_seconds: 5,
          available: true,
          protocol_version: 9,
          slots_total: 10,
          slots_busy: 3,
          slots_available: 7,
          heartbeat_internals: { ignored: true },
        },
      ],
    },
    summary: {
      jobs: 2,
      succeeded: 1,
      failed: 1,
      telemetry_jobs: 2,
      timing_jobs: 2,
      mac_cpu_seconds: 6.5,
      mac_wall_seconds: 8.25,
      peak_rss_bytes: 314_572_800,
      input_bytes: 50_000,
      source_bytes: 20_000,
      result_bytes: 12_000,
      average_queue_seconds: 1.25,
      last_finished_at: 1_774_999_000,
      future_aggregate: { ignored: true },
    },
    tasks: [
      {
        task: 'repo-tests',
        jobs: 1,
        succeeded: 0,
        failed: 1,
        telemetry_jobs: 1,
        cpu_seconds: 4.5,
        wall_seconds: 5.25,
        input_bytes: 40_000,
        peak_rss_bytes: 314_572_800,
      },
      {
        task: 'can-summary',
        jobs: 1,
        succeeded: 1,
        failed: 0,
        telemetry_jobs: 1,
        cpu_seconds: 2,
        wall_seconds: 3,
        input_bytes: 10_000,
        peak_rss_bytes: 104_857_600,
      },
    ],
    jobs: [
      {
        id: '20260826T180000Z-0123abcd',
        task: 'queue-scan',
        state: 'queued',
        worker: null,
        placement: 'pending',
        failure_summary: null,
        submitted_at: 1_774_999_900,
        started_at: null,
        finished_at: null,
        queue_seconds: null,
        active_seconds: 0,
        cpu_seconds: 0,
        peak_rss_bytes: 0,
        input_bytes: 1_000,
        telemetry: false,
      },
      {
        id: '20260826T175000Z-deadbeef',
        task: 'repo-tests',
        state: 'failed',
        worker: 'm4mac',
        placement: 'remote',
        failure_summary: 'Task exited with code 1',
        submitted_at: 1_774_998_000,
        started_at: 1_774_998_001,
        finished_at: 1_774_998_006,
        queue_seconds: 1,
        active_seconds: 5.25,
        cpu_seconds: 4.5,
        peak_rss_bytes: 314_572_800,
        input_bytes: 40_000,
        telemetry: true,
        diagnostics: { stderr: 'producer-owned and intentionally ignored' },
      },
    ],
    eligible_local_work: {
      events: 2,
      cpu_seconds: 36.5,
      wall_seconds: 25.5,
      peak_rss_bytes: 134_217_728,
      input_bytes: 10_000,
      categories: [{ producer_owned: true }],
      reasons: [
        { reason: 'worker-unavailable', events: 1, cpu_seconds: 4 },
        { reason: 'unsupported', events: 1, cpu_seconds: 32.5 },
      ],
      recent: [{ producer_owned: true }],
    },
    benchmark: { producer_owned: true },
    measurement_note:
      'Mac CPU is measured child CPU time; eligible local records are not exhaustive.',
  };
}

export function sampleComputeReport(range: ComputeRange = 168): ComputeReport {
  return decodeComputeReport(computePayload(range));
}
