export function dealWatchPayload(): Record<string, unknown> {
  return {
    ok: true,
    items: [
      {
        id: 7,
        parser: 'amazon',
        threshold: '55.00',
        threshold_cents: 5_500,
        url: 'https://www.amazon.com/dp/B012345678',
        title: 'Protein shakes',
        display_title: 'Protein shakes',
        created_at: 1_725_000_000,
        updated_at: 1_725_100_000,
        last_checked_at: 1_725_100_000,
        last_price: '49.95',
        last_price_cents: 4_995,
        last_price_checked_at: 1_725_100_000,
        last_status: 'ok',
        last_error: null,
        last_title: 'Protein shakes, vanilla',
        notify_muted_until: 1_800_000_000,
        notifications_muted: true,
        below_threshold: true,
      },
      {
        id: 8,
        parser: 'amazon',
        threshold: '25.00',
        threshold_cents: 2_500,
        url: 'https://www.amazon.com/dp/B087654321',
        title: 'Camp stove',
        display_title: 'Camp stove',
        created_at: 1_725_000_100,
        updated_at: 1_725_100_100,
        last_checked_at: 1_725_100_100,
        last_price: null,
        last_price_cents: null,
        last_price_checked_at: null,
        last_status: 'error',
        last_error: 'Amazon product markup changed',
        last_title: null,
        notify_muted_until: null,
        notifications_muted: false,
        below_threshold: null,
      },
    ],
    summary: {
      count: 2,
      checked: 2,
      below_threshold: 1,
      errors: 1,
    },
    searches: [
      {
        id: 12,
        parser: 'ebay',
        url: 'https://www.ebay.com/sch/i.html?_nkw=impact+driver',
        title: 'Impact drivers',
        display_title: 'Impact drivers',
        created_at: 1_725_000_200,
        updated_at: 1_725_100_200,
        last_checked_at: 1_725_100_200,
        last_status: 'ok',
        last_error: null,
        result_count: 1,
        hidden_current_count: 1,
        dismissed_count: 1,
        known_count: 3,
        results: [
          {
            item_id: '123456789012',
            title: 'Milwaukee impact driver kit',
            url: 'https://www.ebay.com/itm/123456789012',
            price: '$119.00',
            shipping: 'Free shipping',
            image_url: '//i.ebayimg.com/images/g/example.jpg',
            first_seen_at: 1_725_090_000,
            last_seen_at: 1_725_100_200,
            dismissed: false,
            dismissed_at: null,
          },
        ],
      },
    ],
    search_summary: {
      count: 1,
      checked: 1,
      results: 1,
      errors: 0,
    },
    schedule: {
      expression: '0 10,15,20 * * *',
      description: 'At minute 0 past hours 10, 15 and 20',
      error: null,
      error_code: null,
    },
  };
}
