#!/usr/bin/env python3
"""Compatibility re-exports for the video identity catalog."""

from __future__ import annotations

__all__ = (
    "CatalogConflict",
    "CatalogError",
    "CatalogNotFound",
    "DEFAULT_BUSY_TIMEOUT_MS",
    "MediaAssetCatalog",
    "SCHEMA_VERSION",
    "ensure_pre_v2_backup",
)

if __package__:
    from .catalog import (
        contextlib as contextlib,
        hashlib as hashlib,
        json as json,
        math as math,
        os as os,
        sqlite3 as sqlite3,
        tempfile as tempfile,
        threading as threading,
        time as time,
        uuid as uuid,
        Iterator as Iterator,
        Mapping as Mapping,
        Path as Path,
        Any as Any,
        Callable as Callable,
        CatalogError as CatalogError,
        CatalogConflict as CatalogConflict,
        CatalogNotFound as CatalogNotFound,
        _json as _json,
        _json_or_none as _json_or_none,
        _digest as _digest,
        _finite_nonnegative as _finite_nonnegative,
        _required_text as _required_text,
        _optional_locator as _optional_locator,
        _path_key as _path_key,
        _new_id as _new_id,
        _backup_path as _backup_path,
        _quick_check as _quick_check,
        ensure_pre_v2_backup as ensure_pre_v2_backup,
        _MIGRATIONS as _MIGRATIONS,
        _V1_UNTRUSTED_COVERAGE as _V1_UNTRUSTED_COVERAGE,
        SCHEMA_VERSION as SCHEMA_VERSION,
        DEFAULT_BUSY_TIMEOUT_MS as DEFAULT_BUSY_TIMEOUT_MS,
        MediaAssetCatalog as MediaAssetCatalog,
    )
else:
    from catalog import (
        contextlib as contextlib,
        hashlib as hashlib,
        json as json,
        math as math,
        os as os,
        sqlite3 as sqlite3,
        tempfile as tempfile,
        threading as threading,
        time as time,
        uuid as uuid,
        Iterator as Iterator,
        Mapping as Mapping,
        Path as Path,
        Any as Any,
        Callable as Callable,
        CatalogError as CatalogError,
        CatalogConflict as CatalogConflict,
        CatalogNotFound as CatalogNotFound,
        _json as _json,
        _json_or_none as _json_or_none,
        _digest as _digest,
        _finite_nonnegative as _finite_nonnegative,
        _required_text as _required_text,
        _optional_locator as _optional_locator,
        _path_key as _path_key,
        _new_id as _new_id,
        _backup_path as _backup_path,
        _quick_check as _quick_check,
        ensure_pre_v2_backup as ensure_pre_v2_backup,
        _MIGRATIONS as _MIGRATIONS,
        _V1_UNTRUSTED_COVERAGE as _V1_UNTRUSTED_COVERAGE,
        SCHEMA_VERSION as SCHEMA_VERSION,
        DEFAULT_BUSY_TIMEOUT_MS as DEFAULT_BUSY_TIMEOUT_MS,
        MediaAssetCatalog as MediaAssetCatalog,
    )
